### ISSUE TITLE
Windows 2012R2 with VirtIO 0.1.126 fails to boot on KVM environment 

### ISSUE THREAD

**Issue by ilenghel** [cloudbase/windows-openstack-imaging-tools#111]
A Windows Server 2012r2 image generated using VirtIO drivers version 0.1.126 (currently latest stable) fails to boot. It seems that this happens because WdfCoInstaller01011.dll is missing from 2k12R2 directory from the ISO file.

Solution: Windows Server 2012R2 and Windows 8.1 share the same kernel so we can use the WdfCoInstaller01011.dll file from 8.1\amd64. Extract the all folders from the VirtIO ISO and copy WdfCoInstaller01011.dll form 8.1\amd64 to 2k12R2\amd64. Also, the $VirtIOBasePath parameter must be set to the location of the directory where the ISO has been extracted.

**Comment by vills** [comment]
This related to https://github.com/crobinso/virtio-win-pkg-scripts/issues/10
Use virtio drivers with version >= 0.1.133-2

**Comment by ader1990** [comment]
Hello,

In the examples, we suggest using the version 2 of those drivers: https://github.com/cloudbase/windows-openstack-imaging-tools/blob/master/Examples/create-windows-cloud-image.ps1#L28

**Comment by vills** [comment]
Version 0.1.126-2 added missed dll only for win8.1, not for 2k12. As @ilenghel mentioned, we can force copy dll from 8.1 directory as it same for 2k12.

So version that works for 2k12 is 0.1.133-2.

From virtio-win changelog:
```
* Mon Mar 13 2017 Cole Robinson <crobinso@redhat.com> - 0.1.133-2
- Add .dll for vioinput on 2k12* (issue #10)
```

**Comment by ader1990** [comment]
Thanks, I have rechecked the ISOs to make sure, and yes, the 133-2 version is the first which has the missing DLL for 2k12r2. I will update in a PR the links.

**Comment by ader1990** [comment]
I have updated the PR: https://github.com/cloudbase/windows-openstack-imaging-tools/pull/118 . @vills can you check it out?

Thank you,
Adrian Vladu

**Comment by ader1990** [comment]
I have merged the PR with the requested changes.
