### ISSUE TITLE
Detach-VirtualDisk Fails and Hangs Windows 10 During VirtIO Driver Copy

### ISSUE THREAD

**Issue by rholloway** [cloudbase/windows-openstack-imaging-tools#113]
I've run into an issue during the build process on Windows 10 that seems new (same build worked about 6 months ago, so I'm wondering if one of these Win 10 updates changed something).

During creation of image, I add virtio drivers for KVM support. Powershell successfully shows the logs stating each driver was copied successfully. At the end, however, it hangs. Not only that, but the whole system becomes pretty non-responsive, windows explorer starts hanging, and the only solution is to physically power cycle the box.

After debugging, it looks like the hanging and issues kick in in the Detach-VirtualDisk function with the call to $v.DetachVirtualDisk() after copying all the drivers from ISO. I'm not sure what causes this. If I reboot, manually mount disk, and then make the same calls in powershell to detach, it works fine.

Anyone know what could cause this lock up?

**Comment by ader1990** [comment]
Hello,

Can you use this branch to test if the issue has been solved?
https://github.com/ader1990/windows-openstack-imaging-tools/tree/use_dismount_vhd

Thank you,
Adrian Vladu

**Comment by ader1990** [comment]
closing issue, as it is more than one year old and it refers to an older backward incompatible image generation tool.
