### ISSUE TITLE
Way to specify 'UnattendXmlPath' argument to 'New-WindowsOnlineImage'

### ISSUE THREAD

**Issue by vills** [cloudbase/windows-openstack-imaging-tools#116]
Don't see any way to pass `UnattendXmlPath` argument to `New-WindowsOnlineImage`, as in `New-WindowsCloudImage`. Is it a bug or feature?

**Comment by ader1990** [comment]
Hello,

This is a "feature" -- as for the online image creation, where the Windows is started as a hyper-v instance, we have a template which we populate with os specific infirmation like architecture and for the final image, we use cloudbase-init's unattend.xml. Do you have a specific requirement in your case?

Thank you,
Adrian Vladu

**Comment by vills** [comment]
Yep, i have so. From changing OS language to firewall rules (or something like in https://github.com/cloudbase/windows-openstack-imaging-tools/pull/81)

**Comment by ader1990** [comment]
To better understand, you would like an option to specify the unattend xml for the Hyper-V instance or for the last sysprep performed after cloudbase-init installation?

**Comment by vills** [comment]
My mistake, sry. Right now i want to pass my own unattend xml for hyper-v instance (when invoking `New-WindowsCloudImage` inside `New-WindowsOnlineImage`)

**Comment by ader1990** [comment]
Feature made available by commit: https://github.com/cloudbase/windows-openstack-imaging-tools/commit/7a77305cc47b9f743626a9bacd94eee404fed310
