### ISSUE TITLE
Image creation gets stuck at Applying image

### ISSUE THREAD

**Issue by Parth6288** [cloudbase/windows-openstack-imaging-tools#122]
Hi Team,
This was working fine for me 5 months back, however now when i try to generate an image using the scripts it gets stuck at DISM /apply-image and doesn't proceed at all. I tried this using ADK 8.1 and ADK 10 still no go. It doesn't allow to stop the process and the only way out is to do a Hard reboot of the VM from the console. Tried this in two different VM and facing similar issue with windows different windows image - tried with 2012R2 and STD wim images.
Even dism mount commands get stuck at around 52%. 
![dismerror](https://cloud.githubusercontent.com/assets/16204776/26148178/70b85a22-3b13-11e7-9237-1bd0d1a340fa.JPG)

**Comment by ader1990** [comment]
Hello,

Make sure you have all the updates to the host where you generate the images and also you can try with a reboot for that host (it usually works).

Thank you,
Adrian Vladu

**Comment by Parth6288** [comment]
Hi @ader1990 , The VM is updated with the latest updates and i have already rebooted it couple of times.  Infact created a new VM, updated it and tried running the scripts, still the same issue. :(

**Comment by ader1990** [comment]
This seems like an environment issue. On what hypervisor are you running the Hyper-V host?

**Comment by Parth6288** [comment]
This is a windows 2012 R2 VM, running on KVM hypervisor.

**Comment by Parth6288** [comment]
I was getting 80070003 error on one of the VM while running windows update, got that fixed, installed remaining updates. Ran dism cleanup scanhealth without and error and started the image creation process - got stuck at 4% of applying image.

In other VM i ran sfc/ scannow found some error in component store which it fixed (it included packages from DISM module - screenshot attached). Started image creation and is now stuck at 7%. Will let it run to see if it gets any further.

![cbs log-imagemgmtserver](https://cloud.githubusercontent.com/assets/16204776/26158231/d320661c-3b38-11e7-8088-3798fe3ea2dd.JPG)

**Comment by ader1990** [comment]
Hello again,

@Parth6288 it worked perfectly for me on a KVM node on centos7 with a windows server 2012r2 core VM and a windows 2012 r2 ISO.
What exactly is your environment?

Thanks,
Adrian Vladu

**Comment by Parth6288** [comment]
We have KVM node with Ubuntu 12.04 on which i use windows 2012R2 server STD (GUI) with windows 2012 R2 ISO.

**Comment by ader1990** [comment]
I am afraid that can be an issue, because of the old qemu-kvm version vs the newer virtio drivers. Can you try using the older virtio drivers: https://fedorapeople.org/groups/virt/virtio-win/deprecated-isos/archives/virtio-win-0.1-52/ for the Windows host and also the Windows vm?

Thank you,
Adrian Vladu

**Comment by Parth6288** [comment]
It worked on a VM on another KVM host in a different data center. i will be checking what went wrong with the previous one. thanks @ader1990

**Comment by ader1990** [comment]
Glad it worked out in the end. Let me know if there are some issues in the imaging tools that we can fix.
On the other hand, you might want to try the newer, simpler way of creating images, based on a configuration (.ini) file: https://github.com/cloudbase/windows-openstack-imaging-tools/tree/experimental

Thank you,
Adrian Vladu
