### ISSUE TITLE
VirtIO drivers require confirmation

### ISSUE THREAD

**Issue by DSpeichert** [cloudbase/windows-openstack-imaging-tools#14]
When building Windows Server 2012 DataCenter with latest VirtIO (virtio-win-0.1-81.iso), during the installation process, the installer asks to confirm the drivers' signature.
There is only a few seconds to do that and if confirmed, everything works fine. If not, the image builds successfully but will die with a blue screen when deployed on a VirtIO devicde.

**Comment by ader1990** [comment]
No longer existent issue, as we force install the drivers without requiring a signature check
