### ISSUE TITLE
"The 'class' keyword is not supported in this version of the language."

### ISSUE THREAD

**Issue by shrekmaxi** [cloudbase/windows-openstack-imaging-tools#159]
I am using Windows7sp1 and I have already installed  .Net Framework. When I tried to import WinImageBuilder.psm1, it throws an error
![image](https://user-images.githubusercontent.com/5965221/29922783-fb224038-8e0b-11e7-9ced-2cef9910ccce.png)

**Comment by ader1990** [comment]
Hello,

This a feature of PowerShell 5, which can be installed on Windows 7 by running the Install-WMF5.1.ps1 from the archive located here: https://download.microsoft.com/download/6/F/5/6F5FF66C-6775-42B0-86C4-47D41F2DA187/Win7AndW2K8R2-KB3191566-x64.zip .

Thank you,
Adrian Vladu
