### ISSUE TITLE
Is there an example of config.ini for bare metal ?

### ISSUE THREAD

**Issue by shrekmaxi** [cloudbase/windows-openstack-imaging-tools#162]
Hi, I am trying to use Maas for deploying windows images into bare metal servers. As I followed  the instruction from https://github.com/cloudbase/windows-openstack-imaging-tools/tree/experimental , I successfully created a windows-2012 image  for MAAS (in my config.ini, "image_type=MAAS "), I noticed the README.MD explicitly shows the supported environments  includes "MAAS with KVM, Hyper-V, VMware and baremetal" . But after the deployment at MAAS, the server keeps rebooting non-stop. So may I ask how should I make any adjustment?
  Thanks

**Comment by shrekmaxi** [comment]
![windows openstack image error001](https://user-images.githubusercontent.com/5965221/30235802-d8affe42-953f-11e7-960b-66a6782a969a.png)

the only info I got from the rebooting server

**Comment by ader1990** [comment]
Hello,

This is a known issue in cloudbase-init which has been fixed in the master branch of cloudbase-init. Please use this config option value in the image configuration file:
[cloudbase_init]
beta_release=true

Thank you,
Adrian Vladu

**Comment by shrekmaxi** [comment]
@ader1990   Thanks so much!  it works
