### ISSUE TITLE
bcdboot.exe : BFSVC Warning: Resource files missing

### ISSUE THREAD

**Issue by Mysteriosis** [cloudbase/windows-openstack-imaging-tools#164]
I try to create a win2012r2 image for MAAS. During the script execution, I got the following error:

```
bcdboot.exe : BFSVC Warning: Resource files missing from F:\windows\boot\Resources. These files are required for some editions of 
Windows. If you are servicing older versions of Windows, you can ignore this message.
At C:\Users\Administrator\Documents\windows-openstack-imaging-tools\WinImageBuilder.psm1:208 char:9
+         & $bcdbootPath ${windowsDrive}\windows /s ${systemDrive} /v / ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (BFSVC Warning: ...e this message.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
```  

There is my PowerShell script:

```Import-Module .\WinImageBuilder.psm1

# The Windows image file path that will be generated
$windowsImagePath = "D:\ISO\win2012hvr2-dd"

# The wim file path is the installation image on the Windows ISO
$wimFilePath = "E:\sources\install.wim"

# Every Windows ISO can contain multiple Windows flavors like Core, Standard, Datacenter
# Usually, the first image version is the Core one
$image = (Get-WimFileImagesInfo -WimFilePath $wimFilePath)[0]

New-MaaSImage -WimFilePath $wimFilePath -ImageName $image.ImageName `
    -MaaSImagePath $windowsImagePath -SizeBytes 16GB -Memory 4GB `
    -CpuCores 2 -DiskLayout BIOS -RunSysprep
```

I tried to re-download a new ISO of Windows Server 2012r2 (just to be sure) but it doesn't change anything...

**Comment by ader1990** [comment]
Hello,

What is the Windows version of the host you are using?

Thank you,
Adrian Vladu

**Comment by Mysteriosis** [comment]
Hi,
I'm on Windows Server 2016 Datacenter.

Thx.

**Comment by ader1990** [comment]
I see the problem you are having is a reoccurring one and I will try to reproduce it in my environment. 
Meanwhile, can you try generating the image using the experimental branch?

Thank you,
Adrian Vladu

**Comment by Mysteriosis** [comment]
I will as soon as I can.
Thank you for your help.

**Comment by ader1990** [comment]
If possible, can you share the following command outputs:
(get-command $env:windir\system32\bcdboot.exe).version
(get-command ${windowsDrive}:\Windows\\system32\bcdboot.exe).version #where $windowsDrive is the mount point of the Windows Server 2012 R2 ISO. Example: "E"

This way, we can have a better understanding of your environment so that we can match it exactly.

Thank you,
Adrian Vladu

**Comment by ader1990** [comment]
Please check this thread too: https://github.com/cloudbase/windows-openstack-imaging-tools/issues/29
It seems the reason might be that your Windows image is corrupted.

From my experience, I found that even downloading an image with Chrome vs Internet Explorer from msdn can get to a failed installation. The images had the same hashes, the only difference being the download method. This happened to me with a SharePoint ISO.

Thank you,
Adrian Vladu

**Comment by Mysteriosis** [comment]
So:
```
PS C:\Users\Administrator> (get-command $env:windir\system32\bcdboot.exe).version

Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      14393  0
```

I can't do the next command, there is no *Windows* folder at the root of my ISO, only *boot*, *efi*, *sources* and *support*...
The dowloading process is an other special thing. I took the image on Dreamspark and I had to download it with a weird "e5 Secure Download Manager" software.

Sorry if I don't understand something, I'm more familiar with Linux systems.

**Comment by Mysteriosis** [comment]
I tried your PR, I got the exact same error :-/
```
bcdboot.exe : BFSVC Warning: Resource files missing from F:\windows\boot\Resources. These files are required for some editions of 
Windows. If you are servicing older versions of Windows, you can ignore this message.
At C:\Users\Administrator\Documents\windows-openstack-imaging-tools-test\WinImageBuilder.psm1:217 char:13
+             & $bcdbootPath ${windowsDrive}\windows /s ${systemDrive}  ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (BFSVC Warning: ...e this message.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
```

Just checked to be sure, I have actually found *bcdboot.exe* in `%windir%\system32\`, as expected.
Still didn't try with experimental branch, I'll try it right now.

**Comment by Mysteriosis** [comment]
Yeah, I doubt you have the same ISO than me, it's a french Dreamspark version:
- File name: `fr_windows_server_2012_r2_x64_dvd_2707985.iso`
- SHA1: `af04c5c20d786989515a50edffea2de94a749c60`

**Comment by ader1990** [comment]
Hello @Mysteriosis ,

I have found the cause of the problem you are facing.
Are you somehow running the script fro PowerShell ISE?

Thank you,
Adrian Vladu

**Comment by ader1990** [comment]
As per https://social.technet.microsoft.com/Forums/windowsserver/en-US/5cf33607-abc5-4715-96b8-b2c056e5b8cb/why-am-i-getting-a-native-command-error?forum=winserverpowershell , it seems that bcdboot.exe opens the error stream and makes PowerShell throw an error, thus not getting to the lastexitcode check. The possible solutions are either to redirect the error stream to the output stream (it did not work in this case) or to have a try/catch block for an exe (why not? this is Powershell). 

I have run the image creation from an administrative PowerShell without the fix and it runs perfectly. If you run the image creation from an elevated PowerShell ISE, it fails with the error you've got. I have added in the PR https://github.com/cloudbase/windows-openstack-imaging-tools/pull/165 the fix, so it should run successfully from normal PowerShell and the PowerShell ISE.

Can you check if the fix solves your problem?

Thank you,
Adrian Vladu

**Comment by Mysteriosis** [comment]
Hi and sorry for the delay.
As expected, everything works fine without ISE. I tried your PR too with ISE and everything went ok.

Thanks a lot for all the work.

**Comment by ader1990** [comment]
Glad to hear that.

Thank you for reporting the issue.
