### ISSUE TITLE
How to do manual Partition ?

### ISSUE THREAD

**Issue by shrekmaxi** [cloudbase/windows-openstack-imaging-tools#167]
I created two images (windows server 2012 & windows server 2008) as the example instructs. But I found both of the images lead to utilization  of whole hard disks being  mounted as only one partition, which is quite disagrees with my goal. Could anyone please tell me how to specify the partition scheme? Thanks

**Comment by ader1990** [comment]
Hello,

There is the possibility of adding additional logic when using the experimental branch, via the custom hooks, which are custom PowerShell scripts that you can define. Here is more information:
https://github.com/cloudbase/windows-openstack-imaging-tools/blob/experimental/Config.psm1#L66

Depending on the script names, they will be executed at various times during the image generation (for example before the updates are installed, etc).

Thank you and let me know if it is what you are looking for,
Adrian Vladu

**Comment by shrekmaxi** [comment]
@ader1990  Thanks for your response,
I noticed there is function called "Create-ImageVirtualDisk" in WinImageBuilder.psm1, inside this function it has  codes like:
`        } else {
            # BIOS
            Initialize-Disk -Number $diskNum -PartitionStyle MBR
            $windowsPart = New-Partition -DiskNumber $diskNum -UseMaximumSize `
                -AssignDriveLetter -IsActive
            $systemPart = $windowsPart
        }`

I was wondering if I can change the size and add new partitions by using this part?

**Comment by ader1990** [comment]
Yes, sure.
I prefer the first variant as I do not need to change the base code.

Thanks.
