### ISSUE TITLE
No ping after instance spin up

### ISSUE THREAD

**Issue by sephiroth4** [cloudbase/windows-openstack-imaging-tools#168]
Hi Team,

After I build the new images with the Examples/create-windows-cloud-image.ps1, Windows 10 does not ping in OpenStack.  I'm only using the virtio drivers that are in the script and a vanilla Windows 10 iso from MS.  My OpenStack team says they modified mkfs.fat in hypervisors to make old images work after an upgrade, but the new upgrade still doesn't make win 10 images pingable.
Openstack creates their disk image and related disk.config and libvirt.xml  files and marks VMs as active but they  are not pingable.  Any pointers?

**Comment by ader1990** [comment]
Hello,

this is an issue usually with the OpenStack Neutron configuration.
Please check if the dhcp server works and if the instance has an IP and if not, if the network adapters drivers are okay (from Device Manager).

Thank you,
Adrian Vladu

**Comment by ader1990** [comment]
closing issue, as it is not related to the image generation, but to an OpenStack configuration problem.
