### ISSUE TITLE
Could not find the Wim file?

### ISSUE THREAD

**Issue by shrekmaxi** [cloudbase/windows-openstack-imaging-tools#172]
when I run : 
git clone https://github.com/cloudbase/windows-openstack-imaging-tools.git
pushd windows-openstack-imaging-tools
git checkout experimental
Import-Module .\WinImageBuilder.psm1
Import-Module .\Config.psm1
Import-Module .\UnattendResources\ini.psm1

$ConfigFilePath = ".\config.ini"
New-WindowsImageConfig -ConfigFilePath $ConfigFilePath

Set-IniFileValue -Path (Resolve-Path $ConfigFilePath) -Section "DEFAULT" `
                                      -Key "wim_file_path" `
                                      -Value "D:\Sources\install.wim"

New-WindowsOnlineImage -ConfigFilePath $ConfigFilePath

I got  an error:
![image](https://user-images.githubusercontent.com/5965221/31850968-3e96b82a-b68f-11e7-9858-3bc4e36cf801.png)

but my wim file is ready(I suppose):
![image](https://user-images.githubusercontent.com/5965221/31850979-673f6132-b68f-11e7-8203-23276966291b.png)

![image](https://user-images.githubusercontent.com/5965221/31850985-7dd22a06-b68f-11e7-802e-45be2d43fdb5.png)

Can anyone figure it out? I actually did it before, but after I closed former terminal. I am in trouble.

**Comment by ader1990** [comment]
Hello,

Make sure you set the image_name accordingly.
In your case, you need to decide what kind of windows flavor you prefer, from the available options listed with dism /get-wiminfo.

Thank you,
Adrian Vladu
