### ISSUE TITLE
About the partition 

### ISSUE THREAD

**Issue by shrekmaxi** [cloudbase/windows-openstack-imaging-tools#176]
Hi, there,
  I have a simple question: how to make the images use partial disk space (like 100G for C:\)instead of using the entire disk as C:\ during the deployment process?
 Thanks

**Comment by ader1990** [comment]
Hello,

You need to manually edit the Unattend.xml file before starting the vm (you are required in this case to use New-WindowsCloudImage, that will create only the VHD, without spawning the VM). Then you need to create/start the VM with that backing VHD file and wait for it to stop. 

You can also leverage the new feature custom_scripts where you can define using diskpart.exe the required partitioning. More details here or in the config.ini generated file: https://github.com/cloudbase/windows-openstack-imaging-tools/blob/experimental/Config.psm1#L68

Thank you,
Adrian Vladu

**Comment by shrekmaxi** [comment]
Thanks for your reply,
 Maybe I was not so precise about my question, what I really want is using the openstack-windows-images for deployment on MAAS. But there is only one problem: After the openstack-windows-images have been deployed into nodes(physical servers), I found the servers only have one partion, and the partitions all are Maximum size of entire disks. just like this:
![openstack-windows-image-ds](https://user-images.githubusercontent.com/5965221/32402267-45a3ed0a-c15b-11e7-9680-b0541212f5cb.jpg)

So any chance the partition size of deployment can be modified?

Thanks

**Comment by ader1990** [comment]
In this case, Cloudbase-Init has a plugin (LocalScripts) that executes scripts located at a configurable path.
You can put in such a script the partitioning scripts.
More details: https://cloudbase-init.readthedocs.io/en/latest/plugins.html#scripts-execution-main

The LocalScriptsPlugin is executed by default.

Thank you,
Adrian Vladu

**Comment by shrekmaxi** [comment]
Is there any tutorial or example for manipulating disk space? 
Thanks
