### ISSUE TITLE
Custom Cloudbase Configuration Options

### ISSUE THREAD

**Issue by henry-spanka** [cloudbase/windows-openstack-imaging-tools#177]
Hello,
I wonder if it's possible to pass configuration options to the Cloudbase-Init installer during New-WindowsOnlineImage? I want to configure several options in the `cloudbase-init.conf`file.

**Comment by ader1990** [comment]
Hello,

This is a feature already on the 'To do' list but is not yet implemented.
However, you can easily define your custom scripts that change the cloudbase-init config options using the hook RunAfterCloudbaseInitInstall.ps1 . More details here or in the config.ini generated file: https://github.com/cloudbase/windows-openstack-imaging-tools/blob/experimental/Config.psm1#L68

Thank you,
Adrian Vladu

**Comment by ader1990** [comment]
Is also very easy to modify the config files (which are ini file) using a crudini like powershell approach. As the custom_scripts will be copied over to the running instance to C:\\UnattendedResources\CustomScripts you can easily import the module https://github.com/cloudbase/windows-openstack-imaging-tools/blob/experimental/UnattendResources/ini.psm1 using a custom script RunAfterCloudbaseInitInstall.ps1 which looks like this:

#ps1 
Import-Module ../ini.psm1

Set-IniFileValue -Path "<cloudbase-init-config-path>"-Section "DEFAULT" -Key "verbose" -Value "true"

**Comment by ader1990** [comment]
This issue is solved by PR #288
