### ISSUE TITLE
About the Admin Account 

### ISSUE THREAD

**Issue by shrekmaxi** [cloudbase/windows-openstack-imaging-tools#191]
Since I have to delete the "Administrator" account after the sysprep (it causes two desktop paths), I need to use the Admin account for the client OS access, so what is the default password for "Admin" (tried passwords in  config.ini & UnattendTemplate.xml, did not work), or How can it be set? Thanks

**Comment by shrekmaxi** [comment]
Thanks for your reply, but I am deploying images on MAAS. Is there any method ?

**Comment by danboid** [comment]
I'm having issues with passwords, MAAS and these scripts. The password I set in config.ini doesn't seem to take effect. I'm no sure if it should be quoted or not.

Seeing as you close this issue I presume you got this resolved @shrekmaxi ?
