### ISSUE TITLE
Accounts Configuration

### ISSUE THREAD

**Issue by shrekmaxi** [cloudbase/windows-openstack-imaging-tools#196]
Hi,
I was wondering if I delete the "Admin" account after I deployed openstack-windows-image (for example: Windows Server 2008r2) into new machines, does it affect any system functions?
Thanks

**Comment by ader1990** [comment]
Hello,

There should not be any problem from cloudbase-init perspective, as it uses another administrative account or localsystem, depending on the configuration.

Thank you,
Adrian Vladu
