### ISSUE TITLE
Unable to boot on baremetal through MAAS

### ISSUE THREAD

**Issue by pb2bee** [cloudbase/windows-openstack-imaging-tools#197]
Hello, I am trying to deploy window 8.1_64bits image on baremetal through MAAS.
I have successfully created win8.1_64bit images through windows-openstack-imaging-tools, and
added the custom image(win8.1_64bit) on MAAS.
Thank you for the convenient and effective the tools.

However, when I start to deploying the image, the baremetal never able to boot from windows.
When the MAAS tried to PXE local boot, the baremetal shows the error like the below.
![img_5287](https://user-images.githubusercontent.com/3312202/38040008-8fe74802-327c-11e8-93ce-b74eadf7b136.JPG)

I have checked the storage information on MAAS, seems everything is fine.

![screen shot 2018-03-28 at 11 26 34 am](https://user-images.githubusercontent.com/3312202/38040078-be1faa02-327c-11e8-9379-4b2f3890d301.png)
![screen shot 2018-03-28 at 11 26 39 am](https://user-images.githubusercontent.com/3312202/38040084-c1622db6-327c-11e8-8b3d-9ecea0725768.png)
![screen shot 2018-03-28 at 11 26 44 am](https://user-images.githubusercontent.com/3312202/38040088-c2f07dd6-327c-11e8-86c4-32df435dfe51.png)

I had no problem when I deployed Ubuntu 16.04 on the baremetal, but Windows image.
I suspected I might missed some options or drivers when I generated the windows image.
Could you tell me how I can tackle this issue? what are the possible mistakes?

thank you,

**Comment by ader1990** [comment]
Hello,

For uefi boot, you need to generate a Windows image accordingly, using disk_layout=UEFI:
https://github.com/cloudbase/windows-openstack-imaging-tools/blob/experimental/Config.psm1#L40

Thank you,
Adrian Vladu

**Comment by pb2bee** [comment]
Thank you for the quick reply. @ader1990 
I have set "UEFI" boot, also $beta_release is "True".
Now I can see the script creates two drives for efi boot section and windows at the beginning of the script.

However, After successfully generated VHD image, 
Now I am struggling with an error in "Resize-VHDImage" at "WinImageBuilder.psm1" like below.
![screen shot 2018-03-28 at 6 51 02 pm](https://user-images.githubusercontent.com/3312202/38060641-9eb7534e-32b9-11e8-8252-222bcd524933.png)

I tried to debug and tried to find which parts yield this error, seems "Optimize-Voulme" yield errors in Resize-VHDImage the code below.
![screen shot 2018-03-28 at 6 52 19 pm](https://user-images.githubusercontent.com/3312202/38060723-ec982566-32b9-11e8-95bc-7e1eb48cb329.png)
 
Could you pinpoint to me how to solve this issue? I have tested with "BIOS" option, never see this error message.

**Comment by ader1990** [comment]
Hello,

I will take a look at this problem, as I have not seen it before.
Nonetheless, you can use the image as it is (you need to manually convert it to raw, and create a tar.gz out of it). Or you can remove the Resize-VHDImage part if it is faster for you.

Thanks.

**Comment by ader1990** [comment]
PR #198 should solve the issue you are having.
Can you give it a try?

Thanks.

**Comment by ader1990** [comment]
I think the problem with the new error is that you have the same vhd mounted multiple times due to previous runs. Can you try to manually unmount the vhd and restart the image generation?

Also, are you sure you are running non-modified code on the experimental branch? as I see an error in the image you posted which should not be there: "$partitionInfo" variable.

Thanks.

**Comment by ader1990** [comment]
@pb2bee can you try with a clean environment to run the code from #198 ?

**Comment by ader1990** [comment]
Hello @pb2bee ,

do you still have this issue

**Comment by pb2bee** [comment]
Unfortunately, Yes. I still see the errors. I have tested with a fresh new machine on Win10 and patched #198, but still see the errors that I had previously. so I had to hard-code the largest driver.

**Comment by laoyin** [comment]
i can deploy windows server r12,

but funny thing is  the grub show ：
    no such file ->/efi/ubuntu/grubx64.efi,

i edit it, change  "/efi/ubuntu/grubx64.efi"  --> /efi/Microsoft/Boot/bootmgfw.efi,

then system booted.


maybe that is maas bug, or i did wrong "create" command to upload the windows image.

**Comment by pb2bee** [comment]
Hi, @laoyin. I am seeing the same error that you have. In my case, the windows8 image was generated with UEFI option. So If I change "/efi/ubuntu/grubx64.efi" --> /efi/boot/bootx64.efi, then the system is successfully booted. I also tested the image in Maas 2.3.3, but I don't see any problem.

**Comment by laoyin** [comment]
@pb2bee i solved this problem, that was really maas bug, 
                 because i am in china, sorry about time difference。

                 there is a uefi template in maas provisioningserver,   maas team defined the centos、windows、rhel、and ubuntu.   just like this.

provisioningserver/templates/ueif/config.local.amd64.template
menuentry 'Local' {
    echo 'Booting local disk...'
    {{if kernel_params.osystem == "windows"}}
    search --set=root --file /efi/Microsoft/Boot/bootmgfw.efi
    chainloader /efi/Microsoft/Boot/bootmgfw.efi
    {{elif kernel_params.osystem == "centos"}}
    search --set=root --file /efi/centos/grubx64.efi
    chainloader /efi/centos/grubx64.efi
    {{elif kernel_params.osystem == "rhel"}}
    search --set=root --file /efi/redhat/grubx64.efi
    chainloader /efi/redhat/grubx64.efi
    {{else}}
    search --set=root --file /efi/ubuntu/grubx64.efi
    chainloader /efi/ubuntu/grubx64.efi
    {{endif}}
}

i am sure that you create custom image in maas, when os.osystem == "custom", the maas local booting will search /efi/ubuntu/grubx64.efi.

there are 2 way you can check your problem,  1:  check your uefi template, and how did you upload your windows8 image. (remember do not use Custom)
         2: try to checkout the postgres, when you are deploying, search for maasserver_node by system_id, checkout the node\s osystem is "windows" or not.
      
if your uefi template is not right, change it, you also can custom it.

if your uefi template is right, image upload is the right way. you should check the maasserver/rpc/boot.py ,  the function--get_config,

in my maas-2.4.0 beta2, there is a bug, they dont give the osystem to the rackd.



forgive my poor english, i wish you can solve you problem. or you can email me   yinxingpan@163.com

**Comment by ader1990** [comment]
Closing the issue, solved by OP.
