### ISSUE TITLE
(Selected vmswit... does not exist:String) [], RuntimeException

### ISSUE THREAD

**Issue by yasmindemiral** [cloudbase/windows-openstack-imaging-tools#205]
Hi
I try to windows-imaging-tools, i run on windows server 2016 and when i run "New-WindowsOnlineImage -ConfigFilePath $ConfigFilePath" command, it gave an error about : 

`PS C:\Users\Administrator\windows-openstack-imaging-tools> New-WindowsOnlineImage -ConfigFilePath $ConfigFilePath
22.06.2018 16:11:09 - Windows online image generation started.
Selected vmswitch external does not exist
At C:\Users\Administrator\windows-openstack-imaging-tools\WinImageBuilder.psm1:1163 char:13
+             throw "Selected vmswitch {0} does not exist" -f $windowsI ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Selected vmswit... does not exist:String) [], RuntimeException
    + FullyQualifiedErrorId : Selected vmswitch external does not exist `

http://paste.openstack.org/show/724119/

How can i solve it ?
Thank you

**Comment by ader1990** [comment]
Hello,

You need to have an external Hyper-V switch named "external", for the online image generation. The switch is used for providing network connectivity to the vm in order for the updates to be installed.
You can configure the switch in the image configuration:

```ini
[vm]
# Used to specify the virtual switch the VM will be using.
# If it is specified but it is not external or if the switch does not exist,
# you will get an error message.
external_switch="external"
```
Thanks,
Adrian

**Comment by willzhang** [comment]
the configuration is default , but how can i create external switch?

```
PS D:\git\windows-openstack-imaging-tools> New-VMSwitch -Name vsexternal -SwitchType external
New-VMSwitch : 无法对参数“SwitchType”执行参数验证。参数“External”不属于 ValidateSet 属性指定的集合“Internal,Privat
e”。请提供一个此集合中的参数，然后重试此命令。
所在位置 行:1 字符: 43
+ New-VMSwitch -Name vsexternal -SwitchType external
+                                           ~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [New-VMSwitch]，ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.HyperV.PowerShell.Commands.NewVMSwitch
```

**Comment by ader1990** [comment]
> can i create

Please see:

https://docs.microsoft.com/en-us/powershell/module/hyper-v/new-vmswitch?view=win10-ps

```ini
-SwitchType
Specifies the type of the switch to be created. Allowed values are Internal and Private. 

To create an External virtual switch, specify either the NetAdapterInterfaceDescription or the NetAdapterName parameter, which implicitly set the type of the virtual switch to External.
```
