### ISSUE TITLE
wim_file_path=E:\sources\install.wim  not found 

### ISSUE THREAD

**Issue by yasmindemiral** [cloudbase/windows-openstack-imaging-tools#206]
I try to run "
New-WindowsOnlineImage -ConfigFilePath $ConfigFilePath" command.
"# The location of the WIM file from the mounted Windows ISO.
wim_file_path=E:\sources\install.wim "

But it gave an error : 

PS C:\Users\Administrator\windows-openstack-imaging-tools> New-WindowsOnlineImage -ConfigFilePath $ConfigFilePath
22.06.2018 16:52:34 - Windows online image generation started.
22.06.2018 16:52:40 - Cloud image generation started.
22.06.2018 16:52:41 - Image WindowsDesktop8 not found in WIM file E:\sources\install.wim
Image WindowsDesktop8 not found in WIM file E:\sources\install.wim
At C:\Users\Administrator\windows-openstack-imaging-tools\WinImageBuilder.psm1:1278 char:9
+         throw ("Image {0} not found in WIM file {1}" -f @($windowsIma ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Image WindowsDe...ces\install.wim:String) [], RuntimeException
    + FullyQualifiedErrorId : Image WindowsDesktop8 not found in WIM file E:\sources\install.wim

But the path is right, it checked again and again. What can i do ? 

Thank you

**Comment by ader1990** [comment]
Hello,

the image name is a standard name which has to be an entry in the wim file, depending on the ISO.

To know what images you can build from a given ISO, mount the ISO and perform:

Get-WimFileImagesInfo -WimFilePath $wimFilePath)
where $wimFilePath should be something like:
$wimFilePath = "D:\Sources\install.wim" # where D: is the ISO mount point.

You can check the examples for how to do it:
https://github.com/cloudbase/windows-openstack-imaging-tools/blob/master/Examples/create-windows-online-cloud-image.ps1#L55

**Comment by yasmindemiral** [comment]
Okey, i checked this "$image = (Get-WimFileImagesInfo -WimFilePath $wimFilePath)" comment and when use i correct image name, code is working.
