### ISSUE TITLE
Cannot set value in ini file

### ISSUE THREAD

**Issue by ksalman** [cloudbase/windows-openstack-imaging-tools#208]
I am trying to create an online image without anything special. From the readme I tried ```New-WindowsOnlineImage -ConfigFilePath $ConfigFilePath``` and I am getting this error. Any ideas how to fix that?
```
PS C:\Users\Administrator\Desktop\windows-openstack-imaging-tools> New-WindowsOnlineImage -ConfigFilePath $ConfigFilePath
6/25/2018 3:58:31 PM - Windows online image generation started.
6/25/2018 3:58:35 PM - Cannot set value in ini file: 3
Cannot set value in ini file: 3
At C:\Users\Administrator\Desktop\windows-openstack-imaging-tools\UnattendResources\ini.psm1:128 char:13
+             throw "Cannot set value in ini file: " + [PSCloudbase.Win ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Cannot set value in ini file: 3:String) [], RuntimeException
    + FullyQualifiedErrorId : Cannot set value in ini file: 3
```

**Comment by ksalman** [comment]
I think it's some kind of permission issue but I cannot figure out what exactly. It does create the config.ini.offile file. Powershell is running as Adminstrator. I tried "Run as Administrator" on cmd, the started powershell from there and I don't see the error.

**Comment by ader1990** [comment]
Hello,

The image generation is required to be run as Administrator. Have you solved the issue by running as Administrator?

Thank you,
Adrian

**Comment by ksalman** [comment]
Yea, I realize that. However the issue is that I see the problem when running Powershell as Administrator. I do not see the problem when I run cmd as Administrator, then starting Powershell from there.

**Comment by ader1990** [comment]
Is "$ConfigFilePath" a relative or absolute path?
ini powershell module does not work with relative paths.

**Comment by ader1990** [comment]
Hello,

I will create a patch to convert the relative path to an absolute path in the ini.psm1 module, to make sure this never happens again. Thanks for the bug report.

**Comment by ader1990** [comment]
Can you try this fix: https://github.com/cloudbase/windows-openstack-imaging-tools/pull/210 ? It should solve this issue.

**Comment by ksalman** [comment]
Hi, thanks for the patch. I tested it and it works.
