### ISSUE TITLE
RunBeforeWindowsUpdates re-running

### ISSUE THREAD

**Issue by ksalman** [cloudbase/windows-openstack-imaging-tools#215]
During an image build, when the VM reboots during updates, it re-runs the RunBeforeWindowsUpdates.ps1 script, is this expected behavior? If the updates need multiple reboots, it re-runs that script every time after a reboot.

**Comment by ader1990** [comment]
Hello,

Yes, this is the intended behavior. Make sure that your hook scripts, like RunBeforeWindowsUpdates are always idempotent, as they might run several times during the Windows generation.

Updates are very cumbersome and hard to manage, as you can never know that another update can be installed after you have installed all of them. You require a reboot (for a state change of Windows) to recognize other applicable updates.

Thanks,
Adrian.

**Comment by ksalman** [comment]
Oh I see, thanks for the clarification.
