### ISSUE TITLE
Windows 7 BCDBoot failed with error

### ISSUE THREAD

**Issue by yasmindemiral** [cloudbase/windows-openstack-imaging-tools#216]
I can create instance on HyperV but i cant run windows-imaging-tool, gives an error this : http://paste.openstack.org/show/725336/

How can i fix this, any idea ?

**Comment by ader1990** [comment]
Hello,

I have reproduced this issue using Win7 iso en_windows_7_professional_with_sp1_x64_dvd_u_676939.iso on a Windows 10 UEFI host. I have created a PR https://github.com/cloudbase/windows-openstack-imaging-tools/pull/217 with the fix.

Can you try it and check if it works?

Thank you,
Adrian Vladu

**Comment by yasmindemiral** [comment]
i use windows server 2016 but it gave same error again

**Comment by yasmindemiral** [comment]
no it does not work. the bcdboot.exe is the host machine ? it is at Windows/System32/bcdboot.exe in windows server 2016 . How can i write it ?

**Comment by yasmindemiral** [comment]
it is not working and error http://paste.openstack.org/show/725529/

**Comment by ader1990** [comment]
Hello,

"no it does not work." - are you sure you have applied the patch from PR https://github.com/cloudbase/windows-openstack-imaging-tools/pull/217 ?

To make sure that you have the right code you need to follow these steps:
```bash
git remote add ader1990 https://github.com/ader1990/windows-openstack-imaging-tools
git fetch ader1990
git checkout fix_win7_bcdboot

# if you have changed the code previously, the checkout might not work correctly, make sure you have a  clean repo clone or you can perform a "git reset --hard"

# to clean your environment from older PowerShell Modules
Remove-Module WinImageBuilder

# now you can restart the image generation

```

**Comment by yasmindemiral** [comment]
I installed windows 10 instead of windows server 2016, i changed manually WinImageBuilder.psm1 but not working. Now i try to change git branch.

**Comment by ader1990** [comment]
I have merged the fix in the master branch, you can use it now.

**Comment by yasmindemiral** [comment]
yes it works.

**Comment by ader1990** [comment]
Great, thanks for reporting the issue and your help testing the fix!
