### ISSUE TITLE
Windows 10 BCDBoot crash

### ISSUE THREAD

**Issue by ksalman** [cloudbase/windows-openstack-imaging-tools#218]
I am trying to create a Windows 10 image on a Windows 2012 R2 server and BCDBoot keeps crashing. I am able to create Windows 7 and Windows 2012 R2 images.

Part where it crashes
```
Deployment Image Servicing and Management tool
Version: 10.0.17134.1

Applying image
[==========================100.0%==========================]
The operation completed successfully.
7/12/2018 9:14:30 PM - Create BCDBoot Config: WIMInterop.WimImage.ImageName...
```
Crash error
```
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	bcdedit.exe
  Application Version:	10.0.15063.0
  Application Timestamp:	8ba6eba4
  Fault Module Name:	api-ms-win-core-heap-l2-1-0.dll
  Fault Module Version:	6.3.9600.18969
  Fault Module Timestamp:	5aa29ff0
  Exception Code:	c0000135
  Exception Offset:	00000000000ecf30
  OS Version:	6.3.9600.2.0.0.400.8
  Locale ID:	1033
  Additional Information 1:	ac05
  Additional Information 2:	ac0507478d1c5bd693cfc4fe3987e900
  Additional Information 3:	ac05
  Additional Information 4:	ac0507478d1c5bd693cfc4fe3987e900

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=280262

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt
```
![image](https://user-images.githubusercontent.com/1268871/42672218-6b893826-8619-11e8-9a63-61a9c37f69b7.png)

When I click on "Close the program" it crashes with the same error again, then again, with the same error. So 3 times in total and the script output looks like this
```
Applying image
[==========================100.0%==========================]
The operation completed successfully.
7/12/2018 9:14:30 PM - Create BCDBoot Config: WIMInterop.WimImage.ImageName...
WARNING: BCDEdit failed: bootmgr device locate
WARNING: BCDEdit failed: default device locate
WARNING: BCDEdit failed: default osdevice locate
7/12/2018 9:21:24 PM - BCDBoot config has been created.
7/12/2018 9:21:26 PM - Cloud image generation finished.
7/12/2018 9:21:26 PM - Creating VM WindowsOnlineImage-Sysprep1136779381 attached to vswitch1

7/12/2018 9:21:27 PM - Starting WindowsOnlineImage-Sysprep1136779381
```
At which point it continues making the image. Though I am not sure how good this image will be. It consistently does this when I try to make a Windows 10 image.

The WIM file is from a 1703 build iso

**Comment by ksalman** [comment]
I let the image build continue and it doesn't look like it's going anywhere. It stops here
![image](https://user-images.githubusercontent.com/1268871/42672581-ab3aac32-861b-11e8-932c-0006f3bd1c4b.png)


Whereas for Windows 7 and Windows 2012 R2, it would login and execute the Logon.ps1 script.

**Comment by ksalman** [comment]
The WIM file is from 1703 build iso. On a whim I tried another iso, and I am not seeing the errors on this one. Though this iso is old - build 10.0.10240, which, I think is older than 1507.

**Comment by ksalman** [comment]
I am seeing the same issue when building a Windows 2016 image.

**Comment by ksalman** [comment]
I installed Windows 2016 on another machine and I am able to build Windows 10 1703 image there, without any errors.  Both servers have the same DISM version, 10.0.17134.1

**Comment by ader1990** [comment]
Issue solved by OP.
