### ISSUE TITLE
KVM Balloon Service (blnsvr.exe) is not installed

### ISSUE THREAD

**Issue by Firefishy** [cloudbase/windows-openstack-imaging-tools#221]
The KVM virtio balloon driver service is not installed. The balloon driver service is required for the VM to release memory back to the host, it should be installed.

To install the virtio balloon service:
1) Copy blnsvr.exe from virtio drivers balloon folder to suitable location.
2) Run blnsvr.exe -i

**Comment by ader1990** [comment]
WiP: https://github.com/cloudbase/windows-openstack-imaging-tools/pull/222

**Comment by ader1990** [comment]
@Firefishy can you check if  #222 solves the issue?

Thanks,
Adrian

**Comment by ader1990** [comment]
Closing the issue, as there was no recent response / activity.
