### ISSUE TITLE
RunAfterSysprep.ps1 does not wait for sysprep to complete

### ISSUE THREAD

**Issue by thorntonryan** [cloudbase/windows-openstack-imaging-tools#223]
## Current Behavior

Currently, sysprep does not execute as a blocking call.

https://github.com/cloudbase/windows-openstack-imaging-tools/blob/f511451ee902a12fc4770d344b50e862c25d573a/UnattendResources/Logon.ps1#L394-L396

As a result, "RunAfterSysprep.ps1" is executed immediately after the call to sysprep, which doesn't appear to be the intent.

For example, in my "RunAfterSysprep.ps1", I have a call to `sdelete`, similar to what's going on [here](
https://github.com/joefitzgerald/packer-windows/blob/c4a111f4f95d311f37ec0f2ae545ffa5407597cb/scripts/compact.bat#L31-L32)

Instead of running `sdelete` and zeroing out all free disk space after `sysprep`, `sdelete` was running while `sysprep` was running....doh!

## Untested Suggestion
I think you might be able to do:
```diff
- & "$ENV:SystemRoot\System32\Sysprep\Sysprep.exe" `/generalize `/oobe `/shutdown `/unattend:"$unattendedXmlPath" 
+ & "$ENV:SystemRoot\System32\Sysprep\Sysprep.exe" `/generalize `/oobe `/shutdown `/unattend:"$unattendedXmlPath | Out-String"  
```

Or instead rely on `Start-Process -Wait` like you do here:
https://github.com/cloudbase/windows-openstack-imaging-tools/blob/f511451ee902a12fc4770d344b50e862c25d573a/UnattendResources/Logon.ps1#L301

**Comment by ader1990** [comment]
Hello,

I understand your requirement, one way would be to not use the shutdown flag for sysprep and wait until it finishes. I will come up with a solution and come back with the patch. We already had a PR for implementing sdelete, will revive it too.

**Comment by ader1990** [comment]
You can now use https://github.com/cloudbase/windows-openstack-imaging-tools/pull/261 to achieve the kind of functionality sdelete provides.
