### ISSUE TITLE
maximum recursion depth exceeded when calling a Python object

### ISSUE THREAD

**Issue by rubenreese** [cloudbase/windows-openstack-imaging-tools#239]
After Sysprep the Windows 2012 image goes into a boot loop with only the error in the command prompt,
"maximum recursion depth exceeded when calling a Python object"

Hoping to get some more information about this error. 
![cap_win-error](https://user-images.githubusercontent.com/654340/51434108-244b7680-1c1f-11e9-9fd6-61bc622ca8a8.PNG)

**Comment by ader1990** [comment]
Hello,

can you try using the beta installer?
config option: https://github.com/cloudbase/windows-openstack-imaging-tools/blob/master/Config.psm1#L127

Thank you,
Adrian Vladu

**Comment by ader1990** [comment]
Closing issue, as no updates were received from the OP.
