### ISSUE TITLE
Creating config.ini

### ISSUE THREAD

**Issue by danboid** [cloudbase/windows-openstack-imaging-tools#251]
One of the comments in the README states:

"# Create a config.ini file using the built in function, then set them accordingly to your needs"

Create a config.ini using which built in function? Function of what? How?

Please make this step clearer in the README. If an external tool is required to create config.ini, please link to it.

**Comment by ader1990** [comment]
Hello,

The script automates the config file generation too:

```
# Create a config.ini file using the built in function, then set them accordingly to your needs
$ConfigFilePath = ".\config.ini"
# this is the built-in function
New-WindowsImageConfig -ConfigFilePath $ConfigFilePath
```

**Comment by danboid** [comment]
Thanks @ader1990, I've never really used powershell so I didn't know what I was looking at. I've got it outputting the ini file now.

**Comment by ader1990** [comment]
@danboid Let me know if there is a problem and how to modify in the docs and I ll make a PR with the change.
Thank you.

**Comment by danboid** [comment]
Will do!

I'll be trying to generate the image tomorrow. I will be able to do that under Windows 10 Ent. I hope ie I don't need to run these scripts under Windows Server for HyperV do I?

**Comment by ader1990** [comment]
You should be able to run it fine as long as https://github.com/cloudbase/windows-openstack-imaging-tools#requirements are met.
