### ISSUE TITLE
Cannot remotely login (as admin) post-install

### ISSUE THREAD

**Issue by danboid** [cloudbase/windows-openstack-imaging-tools#255]
I have enabled `enable_administrator_account` and I have defined a password for `administrator_password` in config.ini. After deploying the image, I have two users available on the login screen -Admin and Administrator. The password specified in config.ini doesn't work for either account and to log in I need to be physically stood in front of the box to set a new password for Administrator.

I want to be able to RDP into the Administrator account straight after deploying.

**Comment by danboid** [comment]
Should the password in config.ini be quoted or not? I didn't use quotes, so maybe that's where I'm going wrong? I don't think the config.ini comment for the password advises about this, and if it only works one way it should be mentioned.

**Comment by danboid** [comment]
I just checked what the comment for the admin password setting says:

"# This will be the Administrator user's, so that AutoLogin can be performed on the instance,
# in order to install the required products,
# updates and perform the generation tasks like sysprep."

Shouldn't that read "This will be the Administrator's password"?

**Comment by ader1990** [comment]
That password is only used for the image generation. After the sysprep is performed, the Administrator account is reset and its password is no longer set. You require console access for the MAAS vm to set the password for the first time.
