### ISSUE TITLE
win 2016 cloudbase init has no  boot log

### ISSUE THREAD

**Issue by sosogh** [cloudbase/windows-openstack-imaging-tools#257]
Hi 

I am  running openstack pike，there are some OS images， such as ubuntu , centos ,win7 ,win 2012.
Today I created a new win 2016 image using create-windows-cloud-image.ps1 , and it can boot .

 But there are some questions:
1. the console log for this win 2016 VM is empty, typically ,it will show quite a lot of cloudbase init log .  other VM (such as win2012 ,ubt ) does has cloud init log.
2. where is the "Cloudbase-Init"  folder in the VM ? typically ,it will be "C:\Program Files\Cloudbase Solutions\Cloudbase-Init" . Even though , I search it ,but can not find it .
3. the VM hostname is not set properly by cloudbase init.

Any hint is appreciated ， THX

> [DEFAULT]
wim_file_path=D:\workspace\2016\Sources\install.wim
image_name=Windows Server 2016 SERVERDATACENTER
image_path=D:\workspace\images\win2016-datacenter-x64.qcow2
virtual_disk_format=QCOW2
image_type=KVM
disk_layout=BIOS
product_key=""
extra_features=""
force=False
install_maas_hooks=False
compression_format=""
zip_password=""
gold_image=False
gold_image_path=""
vmware_tools_path=""
custom_resources_path=""
custom_scripts_path=""
enable_administrator_account=False
wallpaper_path=""
wallpaper_solid_color=""
compress_qcow2=False
extra_packages=""
[vm]
administrator_password=Pa$$w0rd
external_switch=external
cpu_count=1
ram_size=2147483648
disk_size=32212254720
[drivers]
virtio_iso_path=D:\workspace\images\virtio.iso
virtio_base_path=""
drivers_path=D:\workspace\drivers\
[updates]
install_updates=True
purge_updates=True
[sysprep]
run_sysprep=True
unattend_xml_path=UnattendTemplate.xml
disable_swap=True
persist_drivers_install=True
[cloudbase_init]
beta_release=False
serial_logging_port=COM1
msi_path=""

**Comment by ilenghel** [comment]
Hello,

From what you have described, I believe Cloudbase-Init wasn't installed on your image.

Normally, the log files that Cloudbase-Init creates are located in "C:\Program Files\Cloudbase Solutions\Cloudbase-Init\log". Please check if Cloudbase-Init has been installed by looking into Add/Remove Programs in Control Panel.

**Comment by ader1990** [comment]
@sosogh any updated on this issue?
