### ISSUE TITLE
The image can't be use as a iscsi boot?

### ISSUE THREAD

**Issue by YifanShi** [cloudbase/windows-openstack-imaging-tools#258]
I use the image to install on the baremetal local disk . It works well, But if use it as a iscsi boot for ipxe, it throws the error that I have changed the hardware of software ,then it can't go on start

**Comment by ader1990** [comment]
Hello,

Can you share a printscreen of the exact error you are getting?

Thank you,
Adrian

**Comment by ader1990** [comment]
Closing issue, as no updates were received from the OP.
