### ISSUE TITLE
Document prerequisites

### ISSUE THREAD

**Issue by itsbo** [cloudbase/windows-openstack-imaging-tools#27]
Hi,

could you add a description of the necessary environment to run this successfully?

This seems to run on Windows 8.1 but I had trouble getting this to work on 2008R2 where I initially started testing this. (i.e. it didn't work, crashed and somehow locked the created files until I rebooted.).

I managed so far to determine that you need at least

Powershell 3.0
.Net 4.5
ADK

Even on Windows 8.1 it concludes with:

Boot files successfully created.
New-WindowsCloudImage : Exception calling "OpenVirtualDisk" with "1" argument(s): "The system cannot find the file 
specified"
At 
C:\Users\john\Downloads\windows-openstack-imaging-tools-master\windows-openstack-imaging-tools-master\newiso.ps1:21 
char:1
- New-WindowsCloudImage -WimFilePath $wimFilePath -ImageName $image.ImageName `
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [New-WindowsCloudImage], MethodInvocationException
  - FullyQualifiedErrorId : Win32Exception,New-WindowsCloudImage

**Comment by ader1990** [comment]
Hello, we have updated the Readme, also added a few examples.
