### ISSUE TITLE
Windows 2019 Windows Updates in Images FileNotFound Error

### ISSUE THREAD

**Issue by spoer78** [cloudbase/windows-openstack-imaging-tools#284]
Hi there,

i have a problem regarding windows updates during the windows 2019 imaging process. The process runs fine, installs the virtio drivers, boots up the hyper-v vm, syspreps, shuts down and builds the qcow2 image nicely as long as i dont enable the install_updates. If i enable it, i get a FileNotFound Error for the Windows Updates process (which is more or less correct because the folder itself is empty, but i have thought that in that case it would still continue OR even better, install the updates from the internet?! Have i misunderstood something here?

First i thought its an internet connectivity error, but inside the hyper-v vm i can access the internet perfectly fine.

Am i doing something wrong? Is it simply a misconception on my part and i need to provide every Windows Update that i want to install in that directory or else the process gets stuck an no updates are installed? Or is there a config flag where i can enable windows updates from the internet?

Thanks and best regards,
S

**Comment by ilenghel** [comment]
Hello,

If you say your WindowsUpdates directory found inside UnattendResources is empty, please run "git submodule update --init" before generating the image. This should download the needed scripts for the feature to work. Let us know if this helps.

**Comment by spoer78** [comment]
Hi and thanks for the reply,

i think i am more or less a massive douchebag. I haven't forked the repo, i kinda have copied it and created my own "master" in a private Azure repo. So i did not get the module updates. I guess i have to learn git now and see how i can link/merge both (if possible) or at least transfer all the changes from the "real master" to my puny copy '(which i need company-wise)'.

I am sorry and i will give a short feedback after i updated my repo correctly.

Best regards,
S

**Comment by spoer78** [comment]
Works like a charm, thank you and sorry.
