### ISSUE TITLE
Exception in Powershell Script ?

### ISSUE THREAD

**Issue by rcs123** [cloudbase/windows-openstack-imaging-tools#29]
I've downloaded and am trying to run this on Windows.  Unfortunately I keep getting the following errors.

Any ideas ?

PS C:\Users\richard\Documents\cloudbase\windows-openstack-imaging-tools-master\windows-openstack-imaging-tools-master> Import-Module .\WinImageBuilder.psm1
You must provide a value expression on the right-hand side of the '-' operator.
At C:\Users\richard\Documents\cloudbase\windows-openstack-imaging-tools-master\windows-openstack-imaging-tools-master\W
inImageBuilder.psm1:326 char:33
+         if ($VirtualDiskFormat - <<<< in @("VHD", "VHDX"))
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : ExpectedValueExpression

Import-Module : The specified module '.\WinImageBuilder.psm1' was not loaded because no valid module file was found in
any module directory.
At line:1 char:14
+ Import-Module <<<<  .\WinImageBuilder.psm1
    + CategoryInfo          : ResourceUnavailable: (.\WinImageBuilder.psm1:String) [Import-Module], FileNotFoundExcept
   ion
    + FullyQualifiedErrorId : Modules_ModuleNotFound,Microsoft.PowerShell.Commands.ImportModuleCommand

**Comment by ader1990** [comment]
Hello,

Please make sure you have all the requirements installed: https://github.com/cloudbase/windows-openstack-imaging-tools#notes .
In am currently unable to reproduce the error. On what Windows version does it happen?

Thanks.

**Comment by rcs123** [comment]
Thanks for your reply.   

I've upgraded to PowerShell 3.0 (and now Powershell 4.0 too) and the error went away.  The "-In" conditional operator was new in PowerShell 3.0.  

Im running on Windows 7 Professional and it defaults to PowerShell 2.0. 

I also had to put an explicit path to the DISM module into the supplied scripts.
How have you avoided this ? Which env variable did you set ?

Thanks again.

**Comment by rcs123** [comment]
I think I need to get Windows 2012 and try again.
http://stackoverflow.com/questions/14838967/windows-2008-r2-powershell-the-term-get-disk-is-not-recognized-as-the-name-of

I'm seeing an error that Initialize-Disk isn't known and its not available.  I've searched for an answer and it seems I need the Storage Module but according to the above link the Storage Module isn't available in Windows 7!...

If possible could you provide a bit more info with regard to the minimum required to run the scripts.  

Thanks for putting all this together - it will be a great tool once I've managed to get it working !

**Comment by rcs123** [comment]
I've now reinstalled my build environment with Windows 2012r2.
It all works ok until I get to the bcdboot phase and I get this error


E:\windows\system32\bcdboot.exe E:\windows /s E: /f ALL /v
Running bcdboot - "E:\windows\system32\bcdboot.exe E:\windows /s E: /f ALL /v" 
bcdboot.exe : BFSVC Warning: Resource files missing from E:\windows\boot\Resources. These files are required for some editions of Windows. If you are 
servicing older versions of Windows, you can ignore this message.
At C:\users\richard\winbuilder\windows-openstack-imaging-tools-master\windows-openstack-imaging-tools-master\WinImageBuilder.psm1:87 char:5
+     & $bcdbootPath ${driveLetter}:\windows /s ${driveLetter}: /f ALL /v
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (BFSVC Warning: ...e this message.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

Any ideas ? Note I added the /f ALL options to see if that would work.

Thanks
Richard

**Comment by rcs123** [comment]
I've done lots of googling and found a reference that suggested this error can be caused by a corrupt source image.  Apparently even if it installs ok it can be corrupt and happens quite often !

So I downloaded another ISO image of the Windows 2012 Installer (this time the update too) and it worked ok !

The only error I saw (a new error/warning) was that the Installed Version of DISM is older than the Windows Image, but it didn't seem to have a negative effect.

I'll close this issue, now as I've managed to resolve the problems I had, and any further issues will be unrelated.
Thanks
Richard

**Comment by silenceli** [comment]
@rcs123 
Hello, Can you give me the ISO image for windows 2012?
I meet the same question: when execute "& $bcdbootPath ${windowsDrive}\windows /s ${systemDrive} /v /f", the errmsg is: 

"bcdboot.exe : BFSVC Warning: Resource files missing from G:\windows\boot\Resources. These files are required for some editions of Windows. If 
you are servicing older versions of Windows, you can ignore this message."
