### ISSUE TITLE
How to generate mywindowsimage.qcow2

### ISSUE THREAD

**Issue by BrianChangchien** [cloudbase/windows-openstack-imaging-tools#33]
Hi
I use qemucommand " qemu-img create -f qcow2 mywindowsimage.qcow2 8192  " to generate  mywindowsimage.qcow2 , but when run New-WindowsCloudImage , it tell me disk space not enough, can any one tell me how to fix it

**Comment by alexpilotti** [comment]
You need at least 17-20GB for a Windows image
