### ISSUE TITLE
Convert disk image false

### ISSUE THREAD

**Issue by hahnvu** [cloudbase/windows-openstack-imaging-tools#359]
Hello,

I am using windows-openstack-imaging-tools to generate image of Windows Server 2012 R2 for MAAS.

I have tried several times, but it always show "False" at "Convert virtual disk image" step.

I check the qemu-img.exe, and it does exist in .\bin\

Please tell me did i do anything wrong?

In the config file, i change some things like below:

```
# The destination of the generated image.
image_path=D:\imgpath\win2012-image.raw.tgz

# Select between VHD, VHDX, QCOW2, VMDK or RAW formats.
virtual_disk_format=RAW

# This parameter allows to choose between MAAS, KVM, VMware and Hyper-V specific images.
# For HYPER-V, cloudbase-init will be installed and the generated image should be in vhd or vhdx format.
# For MAAS, in addition to cloudbase-init, the curtin tools are installed
# and the generated image should be in raw.tgz format.
# For KVM, in addition to cloudbase-init, the VirtIO drivers are installed
# and the generated image should be in qcow2 format.
image_type=MAAS

# This parameter can be set to either BIOS or UEFI.
disk_layout=UEFI

# If set to true, MAAS Windows curtin hooks will be copied to the image root directory.
install_maas_hooks=True

# Select between tar, gz, zip formats or any combination between these.
compression_format="tar.gz"


```

![image](https://user-images.githubusercontent.com/88580690/128597700-41cdc01e-a51e-4500-b10d-77f0576cc080.png)

**Comment by hahnvu** [comment]
i can manually format VHDX to RAW by this command
![image](https://user-images.githubusercontent.com/88580690/128652969-31fcd684-d773-4a35-a6a3-5b5073370ec1.png)

**Comment by ader1990** [comment]
Hello,

The False output is being generated by other commands, and should not be taken into account, the generation went fine.

**Comment by hahnvu** [comment]
Thank you!
Im going to generate new image try it on MAAS :D

**Comment by pankajmalhotra** [comment]
@hahnvu 
Sorry to ask this question under this section, but how are you uploading windows image to MAAS ?

As when I am uploading the .tgz image which I created this tool and uploading the custom windows 2016 using following command
maas maas boot-resources create name=windows/win2016 architecture=amd64/generic filetype=ddtgz content@=/home/maas/build-output/win2016-image.raw.tgz

I am getting following error, screenshot attached.

![Screenshot 2021-08-11 124807](https://user-images.githubusercontent.com/7905778/129093627-35809e3e-7957-4fc0-9cd2-7a1578fa01f0.png)
![Screenshot 2021-08-11 124827](https://user-images.githubusercontent.com/7905778/129093637-1e838924-1cae-4ee1-b0af-546d177c314e.png)

**Comment by hahnvu** [comment]
Hi @pankajmalhotra,

I use this command to upload image file to MAAS:
`maas admin boot-resources create name=windows/win2012r2 architecture=adm64/generic filetype=tgz title="Windows Server 2012" content@=/home/hanhvd/win-img-bios.raw.tgz`

After uploaded, there will be a file named "root-tgz" in this directory:
`/var/snap/maas/common/maas/boot-resources/current/windows/amd64/generic/win2012r2/uploaded/`

I tried to deploy that image and have the same problem as you. After i checked the error log, i noticed that the client requests the image name "root-dd" instead of "root-tgz". So i rename the image file, from "root-tgz" to "root-dd", and it works 🤣 

I think you should try it. I install MAAS using snap, if you install by deb, the directory path maybe different.

**Comment by pankajmalhotra** [comment]
thanks alot @hahnvu
