### ISSUE TITLE
Mixed CPU infrastructure issues

### ISSUE THREAD

**Issue by T0schi** [cloudbase/windows-openstack-imaging-tools#361]
Hello community,
since we upgraded our OpenStack environmet to Ussurri, we are facing more and more issues with our mixed CPU infrastructure ( Intel and AMD). 
We are creating our Windows images with the imaging tools on a bare metal host with Intel CPU´s. The creation is running fine, the image import to OpenStack also. But when a new instance is spawned and is placed on an AMD host, the VM always runs into a Bluescreen 
![image](https://user-images.githubusercontent.com/56817514/128833849-2e6667f5-609d-40c4-b59b-3c9489f5db22.png)
After a migration ( even to another AMD host) the VM is booting without any problems. 

Now i am struggling where to start searching for the issue. I haven´t found huge changes on Nova in the Ussuri release notes.
Out settings
[libvirt]
inject_partition = -2
inject_password = False
inject_key = False
virt_type = kvm
cpu_mode = custom
cpu_model = Skylake-Server-IBRS
cpu_model_extra_flags = null

As the VM´s are running fine after the migration, i assume that only come CPU flags / Metadata missing, which are set during the  migration. 

Is there a way to have or include a "CPU pre check" in the created images or is it an issue only related to Nova which has to be addressed there?

**Comment by ader1990** [comment]
Hello,

I think putting setting this flag to false might work:
https://github.com/cloudbase/windows-openstack-imaging-tools/blob/master/Config.psm1#L130

Thank you,
Adrian Vladu

**Comment by T0schi** [comment]
Hi Adrian, thank you for the hint but changing this setting result in Bluescreens on every Boot on a AMD host, even after a migration (on Intel hosts everything is running fine). I´ve checked it with several Windows versions.
Any other idea? 
If not, i think we have to test it with "cpu_mode = host-model" in nova.
