### ISSUE TITLE
Windows 7 BCDboot Error

### ISSUE THREAD

**Issue by rohagan** [cloudbase/windows-openstack-imaging-tools#38]
Been trying to create a Windows 7 Image, Tried 3 different hosts and keep getting this error,
###### 

Deployment Image Servicing and Management tool
Version: 6.3.9600.17031

Applying image
[==========================100.0%==========================]
The operation completed successfully.

Bcdboot - Bcd boot file creation and repair tool.

The bcdboot.exe command-line tool is used to copy critical boot files to the
system partition and to create a new system BCD store.

bcdboot <source> [/l <locale>] [/s <volume-letter>] [/v]
                 [/m [{OS Loader ID}]]

  source            Specifies the location of the windows system root.

  /l                Specifies an optional locale parameter to use when
                    initializing the BCD store. The default is US English.

  /s                Specifies an optional volume letter parameter to designate
                    the target system partition where boot environment files are
                    copied.  The default is the system partition identified by
                    the firmware.

  /v                Enables verbose mode.

  /m                If an OS loader GUID is provided, this option merges the
                    given loader object with the system template to produce a
                    bootable entry. Otherwise, only global objects are merged.

Examples: bcdboot c:\windows /l en-us
          bcdboot c:\windows /s h:
          bcdboot c:\windows /m {d58d10c6-df53-11dc-878f-00064f4f4e08}
BCDBoot failed
At C:\windows-openstack-imaging-tools-master\WinImageBuilder.psm1:99 char:25
-     if($LASTEXITCODE) { throw "BCDBoot failed" }
-                         ~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : OperationStopped: (BCDBoot failed:String) [], RuntimeException
  - FullyQualifiedErrorId : BCDBoot failed
###### 

Thanks!

**Comment by omermahgoub** [comment]
I'm getting the same error on Windows 2008 R2. 
It's already mentioned that older versions of bcdboot.exe don't have a /f argument. Trying changing the switches throw error exception.

Any help is really appreciated.
Thanks

**Comment by markchuman** [comment]
Not sure if this is related, but it is a bcdboot.exe related error I'm hitting.

`PS C:\mark\windows-openstack-imaging-tools-master> .\image_create.ps1


Handle                  : WIMInterop.NativeMethods+WimImageHandle
ImageIndex              : 1
ImageName               : Microsoft Windows PE (x64)
ImageEditionId          : WindowsPE
ImageFlags              :
ImageProductType        : WinNT
ImageInstallationType   : WindowsPE
ImageDescription        : Microsoft Windows PE (x64)
ImageSize               : 2487257353
ImageArchitecture       : AMD64
ImageDefaultLanguage    : en-US
ImageVersion            : 6.3.9600.16384
ImageDisplayName        :
ImageDisplayDescription :

WARNING: "E:\windows\system32\bcdboot.exe" not found, using online version
BFSVC Error: Failed to validate boot manager checksum (E:\windows\boot\PCAT\bootmgr)! Error code = 0xc1
Failure when attempting to copy boot files.
BCDBoot failed
At C:\mark\windows-openstack-imaging-tools-master\WinImageBuilder.psm1:138 char:25
+     if($LASTEXITCODE) { throw "BCDBoot failed" }
+                         ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (BCDBoot failed:String) [], RuntimeException
    + FullyQualifiedErrorId : BCDBoot failed`

**Comment by ader1990** [comment]
fixed commited
