### ISSUE TITLE
Can you use Windows 10 to generate the Image for Windows Server 2012 R2

### ISSUE THREAD

**Issue by Shuliyey** [cloudbase/windows-openstack-imaging-tools#43]
Hi,

Just wondering can you use Windows 10 as the host to generate the Image for Windows Server 2012 R2. Also With the Windows ADK installation, does it matter the install location where you put the program?

This is the location of where I installed Windows ADK, as my C drive is running out of space :smile: 

![image](https://cloud.githubusercontent.com/assets/4773348/13063650/60e6b918-d49e-11e5-9a3a-17ff416cb7a1.png)

**Comment by markchuman** [comment]
not sure about generating server 2012r2 from windows 10, but if you are using windows 10 as the host you shouldn't need the development kit for dism (not sure if that's the piece you were after) as windows 10 has it by default. - https://technet.microsoft.com/en-us/library/hh825010.aspx - 
Install the Windows Assessment and Deployment Kit (Optional)
The DISM PowerShell module is included in Windows 8.1 and Windows Server 2012 R2. On other supported operating systems, you can install the Windows Assessment and Deployment Kit (Windows ADK) which includes the DISM PowerShell module. For more information, see Installing the Windows ADK.

**Comment by missingcharacter** [comment]
Windows ADK for windows 10 is here https://blogs.technet.microsoft.com/yongrhee/2015/08/11/download-windows-10-assessment-and-deployment-kit-adk/

**Comment by ader1990** [comment]
closing issue, as it the requirements have been added to the readme page.
