### ISSUE TITLE
Not an issue, just a little praise

### ISSUE THREAD

**Issue by The-Oracle** [cloudbase/windows-openstack-imaging-tools#46]
I am glad to see that you added the proper conditional statements to install VirtIO drivers correctly, I wrote the same exact code back in October. I like your addition of fixing the BCD File. I realized that had to be done but i just commented out the image conversion and after the script ran remounted the VHD, ran a fixboot, fixmbr, and rebuildbcd using bootrec, then unmounted the VHD and manually converted the VHD over to the OpenStack destination format.

**Comment by ader1990** [comment]
Thank you :)
