### ISSUE TITLE
Desktop Background

### ISSUE THREAD

**Issue by Shuliyey** [cloudbase/windows-openstack-imaging-tools#48]
Hi 

Just wondering, are we able to change the desktop background?

![image](https://cloud.githubusercontent.com/assets/4773348/13208439/236cd634-d96d-11e5-8844-02831b8cd92d.png)

I've tried to manually change the desktop background, but seems like there're restrictions on doing this. The background doesn't change after **"Save changes"** is pressed

**Comment by tomcsanyid** [comment]
Replacing the Wallpaper.png file does the trick.

**Comment by lukaskl** [comment]
Having the same problem, could you give a little bit more information where to found this "Wallpaper.png", because I couldn't find it and closes what I got was "Wallpaper-Cloudbase-2013.png" in "C:\Windows\Web\Wallpaper\Cloudbase". Also modifying this found image gave no results.

**Comment by domi007** [comment]
@lukaskl https://github.com/cloudbase/windows-openstack-imaging-tools/blob/master/UnattendResources/Wallpaper.png

**Comment by markchuman** [comment]
Is the wallpaper adjusted to a cloudbase related image even if we are working from a non-cloudbase iso?

**Comment by wilkemeyer** [comment]
gpedit.msc -> User Configuration -> Administrative Templates -> Desktop -> Desktop 

Disable Desktop Wallpaper Policy & you'll be fine

**Comment by ader1990** [comment]
closing issue, as the solution has been described in the above comment.
