### ISSUE TITLE
New-WindowCloudImage: The variable '$v' cannot be retrieved

### ISSUE THREAD

**Issue by rollenburger** [cloudbase/windows-openstack-imaging-tools#57]
I am receiving the following error when trying to build a 2008 R2 qcow2 image:

```
New-WindowsCloudImage : The variable '$v' cannot be retrieved because it has not been set.
At C:\Images\windows-openstack-imaging-tools-master\build-2008r2-kvm.ps1:21 char:5
+     New-WindowsCloudImage -WimFilePath $wimFilePath -ImageName $image.ImageName  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (v:String) [New-WindowsCloudImage], RuntimeException
    + FullyQualifiedErrorId : VariableIsUndefined,New-WindowsCloudImage
```

Here is my build script:

```
Import-Module .\WinImageBuilder.psm1


$virtualDiskPath = "C:\Images\windows-openstack-imaging-tools-master\win2008r2-002.qcow2"

$wimFilePath = "C:\Images\windows-openstack-imaging-tools-master\2008r2-src\sources\install.wim"

$virtIOISOPath = "C:\Images\windows-openstack-imaging-tools-master\virtio-win-0.1-81.iso"

$images = Get-WimFileImagesInfo -WimFilePath $wimFilePath

$image = $images[0]
$image

New-WindowsCloudImage -WimFilePath $wimFilePath -ImageName $image.ImageName -VirtualDiskFormat QCow2 -VirtualDiskPath $virtualDiskPath -SizeBytes 16GB -VirtIOISOPath $virtIOISOPath

```

Any ideas?

**Comment by markchuman** [comment]
Is this the location of the script you have referenced here? - C:\Images\windows-openstack-imaging-tools-master\build-2008r2-kvm.ps1.

I would try again without adjusting the location of these variables:

$virtualDiskPath, $wimFilePath, $virtIOISOPath

The only thing that may need adjusting is the name of the virtio iso.

$virtIOISOPath = "C:\ISO\virtio-win-0.1-81.iso" to $virtIOISOPath = "C:\ISO\virtio-win-0.1.102.iso"

I say try this route first as I adjusted the location of these variables and then found that subsequent scripts that are called in the "windows-openstack-imaging-tools-master" directory are actually calling to the locations listed in the initiation script.

**Comment by ader1990** [comment]
Added examples scripts in the Examples volume if you encounter this issue again.
