### ISSUE TITLE
Windows 2008 R2 and 2012 STD Windows updates does not work

### ISSUE THREAD

**Issue by Parth6288** [cloudbase/windows-openstack-imaging-tools#66]
Hi Team,

Following to the suggestion provided by Adrian creating a new forum for the windows update issue.

Windows 2008 R2 updates was working till couple of days back which has now stopped working. Windows 2012 STD never worked for WSUS updates. we have our central WSUS server which we use for Windows updates and I also created a new WSUS server just to test these images. However it does not work with either of them. The challenge is the WSUS updates does not work during the logon script execution however if I stop the script, extract the content of PSWidowsupdate to powershell Module folder import the module and call Get-WUInstall it works perfectly fine. This behavior is same for both Windows 2008 R2 and 2012 STD. 

Thanks,
Parth

**Comment by ader1990** [comment]
Hello,

I have a question on when and how do you set the wsus server uri? This is important, because if you set it after the logon script has started, the windows updates install will fail.

Thank you.

**Comment by Parth6288** [comment]
Hi,
I am setting it up in the logon script itself just before unzipping the PSWindowsupdate module. Below is the code that I am using the set the uri.

# Set up the registry values to WSUS server
	$WindowsUpdateRegKey = "HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate\AU"
	$WindowsUpdateRootRegKey = "HKLM:\Software\Policies\Microsoft\Windows\WindowsUpdate\"
	$WSUSServer = "http://mywsusserveruri/"
	$StatServer = "http://mywsusserveruri/"
	$Enabled = 1

# Test if the Registry Key doesn't exist already
if(-not (Test-Path $WindowsUpdateRegKey))
{
    # Create the WindowsUpdate\AU key, since it doesn't exist already
    # The -Force parameter will create any non-existing parent keys recursively
    New-Item -Path $WindowsUpdateRegKey -Force
}

# Enable an Intranet-specific WSUS server
Set-ItemProperty -Path $WindowsUpdateRegKey -Name UseWUServer -Value $Enabled -Type DWord

# Specify the WSUS server
Set-ItemProperty -Path $WindowsUpdateRootRegKey -Name WUServer -Value $WSUSServer -Type String

# Specify the Statistics server
Set-ItemProperty -Path $WindowsUpdateRootRegKey -Name WUStatusServer -Value $StatServer -Type String

**Comment by Parth6288** [comment]
Attached is the error that I get for Windows 2012 STD 
![2012std](https://cloud.githubusercontent.com/assets/16204776/18511867/e5719062-7aa3-11e6-918b-d9133253717b.JPG)

**Comment by Parth6288** [comment]
Hi Team,

I still continue to face the issue with Windows 2012 STD.

Thanks,
Parth

**Comment by Parth6288** [comment]
Hi,
I tried using the windowsupdateCLI module for Windows Update however still unable to get it working. below is the link to my logon.ps1 file.
http://pastebin.com/Ahp8vCLM

Please advice if i am missing anything.

Thanks.

**Comment by ader1990** [comment]
For the moment, the windowsupdatecli module is not compatible with a wsus server. We are working on it   to offer support for wsus.

**Comment by Parth6288** [comment]
Thanks, Adrian. I was able to use the script for one of my test VM to install updates through wsus using this module. However it does not work with the logon script. Appreciate if you can please comment once it is fixed.

**Comment by Parth6288** [comment]
Hi @ader1990 , Please advice if windowsupdateCli is now working with WSUS or not.

**Comment by ader1990** [comment]
Hello @Parth6288 ,

You can try changing this value for the windowsupdatecli to see if it works in your environment: https://github.com/ader1990/WindowsUpdateCLI/blob/master/WindowsUpdates/WindowsUpdates.psm1#L19

In your case, it should be either 0 or 1. More information you can find here: https://msdn.microsoft.com/en-us/library/windows/desktop/aa387280(v=vs.85).aspx

Let me know if this works for you.

Thanks, Adrian Vladu

**Comment by Parth6288** [comment]
thanks @ader1990 , It seems to be working now with Windows 2012 STD and 2008 R2. It is however taking a lot of time to install the updates( around 6-7 hours in 2012 STD and more than 10 hours in 2008 R2). Is this how it is with Windows update as well or could be with my environment. I am doing multiple test in our environment for this.

**Comment by ader1990** [comment]
@Parth6288 did it work with a 0 or 1? If it is possible, can you do a PR with the code that worked for you?

Thanks.

**Comment by Parth6288** [comment]
Hi @ader1990  it worked with value 1. I have created a pull request with the modified code. Thanks for all the help in getting this resolved. I will try creating the actual image once December month patches are released. :)
