### ISSUE TITLE
Does it support building ironic baremetal windows image?

### ISSUE THREAD

**Issue by silenceli** [cloudbase/windows-openstack-imaging-tools#70]
I search on the internet, I didn't find any tools support building windows images for Ironic. Even any useful manual except some blueprints and some PPTs.

1. I use ironic in master branch and other components are mitaka branch
2. use cloudbase windows image, download from: https://cloudbase.it/windows-cloud-images/
3. use pxe_ipmitool driver
	Anything is OK, but after dd the image(the raw windows image that is converted from cloudbase windows image) to the baremetal node's disk. baremetal reboot meet error: 
![2](https://cloud.githubusercontent.com/assets/1579708/20296188/53af7b18-ab44-11e6-8a7a-66e1f8db0ab3.jpg)

**Comment by ader1990** [comment]
Hello,

The image generation tool does support baremetal OpenStack generation. Please use the code from this PR: https://github.com/cloudbase/windows-openstack-imaging-tools/pull/63

The issue that you are getting - BSOD due to storage failure -- is probably related to the storage drivers not being installed.

Are you using the KVM image version for testing?

Thanks,
Adrian Vladu

**Comment by silenceli** [comment]
Thanks
yes, I use the KVM image version for testing.
I will try you code to build baremetal windows image

**Comment by silenceli** [comment]
Can you give me a example how to use windows-openstack-imaging-tools to build ironic baremetal windows 2012 image? @ader1990

Thank you very much,
Hank Li

**Comment by silenceli** [comment]
now I have built windows 2012 successfully.  windows-openstack-imaging-tools have little problem when I build. 
    # Note: older versions of bcdboot.exe don't have a /f argument
    if ($image.ImageVersion.Major -eq 6 -and $image.ImageVersion.Minor -lt 2) {
        & $bcdbootPath ${windowsDrive}\windows /s ${systemDrive} /v
    } else {
        & $bcdbootPath ${windowsDrive}\windows /s ${systemDrive} /v /f $diskLayout
    }

& $bcdbootPath ${windowsDrive}\windows /s ${systemDrive} /v /f $diskLayout
should be changed to:
& $bcdbootPath ${windowsDrive}\windows /s ${systemDrive}

**Comment by silenceli** [comment]
I use windows-openstack-imaging-tools to build windows 2008 ironic image. it can produce a image, but when I upload it to glance,and use it to create a baremetal node, It still meet bluescreen.

I have already put the LSI SAS driver into the designated Folder. so can anyone help me? thank you

**Comment by silenceli** [comment]
I add some change to codes in master branch 
[file1.txt](https://github.com/cloudbase/windows-openstack-imaging-tools/files/782484/file1.txt)
and I write a new ps1 file to call New-WindowsOnlineImage:

`$ErrorActionPreference = "Stop"

#git submodule update --init
Import-Module ./WinImageBuilder.psm1


#-------------------------------param--------------------------------------------------
$isIronicImage = $true
$basePath = "C:\images"
$outputImageName = "my-windows-image-2012-8.raw"
# The wim file path is the installation image on the Windows ISO
$wimFilePath = "F:\Sources\install.wim"
# Extra drivers path contains the drivers for the baremetal nodes
# Examples: Chelsio NIC Drivers, Mellanox NIC drivers, LSI SAS drivers, etc.
# The cmdlet will recursively install all the drivers from the folder and subfolders

#$extraDriversPath = "C:\drivers\"

# Every Windows ISO can contain multiple Windows flavors like Core, Standard, Datacenter
# Usually, the second image version is the Standard one
$image = (Get-WimFileImagesInfo -WimFilePath $wimFilePath)[3]
#$image = (Get-WimFileImagesInfo -WimFilePath $wimFilePath)[0]
#may change 4, for windows 2012
#12 XXXXX-XXXX-XXXXX-XXXXX-XXXXX
#08 XXXXX-XXXX-XXXXX-XXXXX-XXXXX
#$productKey = 'XXXXX-XXXX-XXXXX-XXXXX-XXXXX'
$productKey = 'XXXXX-XXXX-XXXXX-XXXXX-XXXXX'
#-------------------------------param--------------------------------------------------

# The Windows image file path that will be generated
$windowsImagePath = $basePath + "\" + $outputImageName


# VirtIO ISO contains all the synthetic drivers for the KVM hypervisor
if (!$isIronicImage)
{
    $VirtIOISOPath = $basePath + "\virtio.iso"
    $isExist = Test-Path -Path $VirtIOISOPath

    if (! $isExist)
    {
        #no need change
        $virtIODownloadLink = "https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/virtio-win-0.1.126-2/virtio-win.iso"

        # Download the VirtIO drivers ISO from Fedora
        Write-Output "downloading virtio driver..."
        (New-Object System.Net.WebClient).DownloadFile($virtIODownloadLink, $VirtIOISOPath)
        Write-Output "download virtio driver finished"
    }
    else
    {
        Write-Output "virtio driver is already exist"
    }
}
# Make sure the switch exists and it allows Internet access if updates
# are to be installed
$switchName = 'br100'

# This scripts generates a raw tar.gz-ed image file, that can be used with MAAS
# if you build VM image. please add -VirtioISOPath $virtIOISOPath
if ($isIronicImage)
{
    New-WindowsOnlineImage -WimFilePath $wimFilePath -ImageName $image.ImageName `
        -WindowsImagePath $windowsImagePath -Type 'MAAS' -ExtraFeatures @() `
        -SizeBytes 30GB -CpuCores 4 -Memory 4GB -SwitchName $switchName `
        -ProductKey $productKey -DiskLayout 'BIOS' `
        -ExtraDriversPath $extraDriversPath `
        -InstallUpdates:$false -AdministratorPassword 'Abcd12345' `
        -PurgeUpdates:$false -DisableSwap:$true
}
else
{
    New-WindowsOnlineImage -WimFilePath $wimFilePath -ImageName $image.ImageName `
        -WindowsImagePath $windowsImagePath -Type 'MAAS' -ExtraFeatures @() `
        -SizeBytes 30GB -CpuCores 4 -Memory 4GB -SwitchName $switchName `
        -ProductKey $productKey -DiskLayout 'BIOS' -VirtioISOPath $virtIOISOPath `
        -ExtraDriversPath $extraDriversPath `
        -InstallUpdates:$false -AdministratorPassword 'Abcd12345' `
        -PurgeUpdates:$false -DisableSwap:$true
}
`

**Comment by silenceli** [comment]
I have already built windows 2008 image, with the correct LSI SAS driver.

**Comment by luoyancn** [comment]
@silenceli ，hi, could you tell me where to down load the correct LSI SAS drivers?

**Comment by ader1990** [comment]
@luoyancn The LSI SAS drivers depend on the storage controller of your server and the Windows version.
Usually, the OEM provides the Windows drivers for download.

Thank you,
Adrian Vladu
