### ISSUE TITLE
Windows 2012 R2 Ent with over 64GB of RAM

### ISSUE THREAD

**Issue by jrich523** [cloudbase/windows-openstack-imaging-tools#84]
I used the script to build an image, which worked well, however now that im spinning up VMs with it i've come across an issue with VMs that have over 64GB of RAM. After the creation of an instance as windows boots I get the following error

Windows could not finish configuration the system. To attempt to resume configuration, restart computer.

So, i restart it and it ends up back at the same error message.

Thoughts?

**Comment by ader1990** [comment]
Hello,

Can you give more information related to the setup you have: what hypervisor, RAM given to the vm?

Thank you,
Adrian Vladu

**Comment by ader1990** [comment]
Hello again,

I have found the issue you are facing -- is related to the swap size. Basically, the swap size is by default computed by Windows at boot time and is proportional to the available RAM. In your case, the swap size is bigger than the size of the initial disk (as OpenStack does not expand the partition automatically before instance boot). 

The imaging tool has already an option: DisableSwap, which you need to set on $True: https://github.com/cloudbase/windows-openstack-imaging-tools/blob/master/WinImageBuilder.psm1#L892

If the DisableSwap option is set to $True, before sysprep the swap will be set to 0 and at the first boot time, during specialize and after cloudbase-init has expanded the partitions, the swap will be set to the default Windows value (automatically managed).

Let me know if you have any questions on the solution.

Thank you,
Adrian Vladu

**Comment by jrich523** [comment]
Awesome, that makes sense. I'll give it a try.

Thanks!
