### ISSUE TITLE
INACCESSIBLE_BOOT_DEVICE

### ISSUE THREAD

**Issue by david-hill** [cloudbase/windows-openstack-imaging-tools#9]
Hi Alex,

   First of all, this is great!  I tried it and it works flawlessly with WS2012R2 but I'm less fortunate with WS2012 as I get INACCESSIBLE_BOOT_DEVICE when I try to boot the VM in KVM with the virtio drivers ...  Did you do anything different for that OS?

Dave

**Comment by rcs123** [comment]
Did you resolve this ? I'm having the same problem ?  It boots the Windows VM in Openstack , but the Windows boot manager via the console view complains about a change in hardware and gives error 0xc00000001
If I reboot it tries to restart several times but always gives the same error.

**Comment by ader1990** [comment]
Hello,

First of all, you need to use kvm(hardware acceleration), and not qemu, when running Windows as a vm with qemu-kvm. If you are using OpenStack, you can enable in your nova compute node's nova.conf, in the [libvirt] section, virt_type = kvm. Secondly, you need to install the virtio drivers on Windows if you are using a virtio device(virtio-net adapter type or virtio-scsi disk type). The drivers can be found here http://alt.fedoraproject.org/pub/alt/virtio-win/stable/.

Thanks.

**Comment by rcs123** [comment]
Hi

I checked and double checked and found I was doing everything as you describe.  I ran the powershell through the Power Shell ISE Debugger and stopped in the module AddVirtIODriversFromISO, in the WinImageBuilder.psm1 file as this seemed to be driver related.

I'm using Windows 2012R2 Update with Image Version of 6.3.9600.17415
I'm using the latest virtio drivers virtio-win-0.1.102.iso

I  found that the $image.ImageVersion.Major was reporting as 6, but the $image.ImageVersion.Minor was 3.
However in the AddVirtIODriversFromISO function, these values were setting the $virtioVer to "8.1" for Windows 8.1 and not "2k12r2" for Windows 2012.  I've amended it and rerun, and now the VM Instance Launches and configures itself in OpenStack, definately getting passed the problem I had above.

If I'm right ... It looks like a bug in the  AddVirtIODriversFromISO function. There seems to be a duplicate section of code with the same version number tests for later versions of Windows.... At least one of the tests is wrong.

**Comment by derjohn** [comment]
@rcs123 https://github.com/derjohn/windows-openstack-imaging-tools/commit/74c8612fc2e5bce25ef9d96e5af2c0cd3584b2b1

**Comment by jackchenjie** [comment]
i meet some problem. when i deploy windows server 2012 by ironic on inspur server .

the system is appear to windows_boot_manager  

error_code: status:0xc0000001

the picture:

INACCESSIBLE_BOOT_DEVICE

**Comment by jackchenjie** [comment]
@ader1990

**Comment by ader1990** [comment]
Hello, 

The problem you have is definitely a storage controller driver problem. Please check on the oem's website for the Windows Server storage drivers and you can add them to the image using the DriversPath parameter. 

Thank you, 
Adrian Vladu

**Comment by jackchenjie** [comment]
hi ader:
@ader1990  error_logs:
![248_inspur](https://cloud.githubusercontent.com/assets/27796664/26442549/8fa5daea-4167-11e7-98af-9aafb39b7fcd.png)
![ironic_windows_deploy_error](https://cloud.githubusercontent.com/assets/27796664/26442548/8fa5c41a-4167-11e7-84c8-e2760f8b3189.png)

**Comment by jackchenjie** [comment]
hi ader:
 
i add servers SATA driver to windows server 2012 image , and i use ironic deploy windows serve 2012,appear to new error:

error_logs:

windows boot manager

file:\windows\System32\drivers\arcsas.sys 

status: 0xc0000359

@ader1990

**Comment by ader1990** [comment]
At first, as a best practice, you can attach a windows iso to the machine, attach the drivers device (which can be a virtual usb or another iso) and then load manually the drivers if no disks are found.

Thank you,
Adrian Vladu

On May 25, 2017 11:59 AM, jackchenjie <notifications@github.com> wrote:

hi ader:

i add servers SATA driver to windows server 2012 image , and i use ironic deploy windows serve 2012,appear to new error:

error_logs:

windows boot manager

file:\windows\System32\drivers\arcsas.sys

status: 0xc0000359

@ader1990<https://github.com/ader1990>
