### ISSUE TITLE
Support install.esd images

### ISSUE THREAD

**Issue by embray** [cloudbase/windows-openstack-imaging-tools#98]
Windows 10 images (at least) obtained through Microsoft's Electronic Software Download system seem to not contain an install.wim image, but rather an install.esd.  I don't know how much trouble it would be to write tools to read directly out of an esd image, but they can be converted to wim images using the [`dism`](https://msdn.microsoft.com/en-us/windows/hardware/commercialize/manufacture/desktop/dism-image-management-command-line-options-s14) utility.

Would it make sense to add support for this directly in the WinImageBuilder.psm1 module?

**Comment by ader1990** [comment]
Hello, @embray . We can add a source suffix check and do a dism conversion in a temp folder if needed.

**Comment by embray** [comment]
That's what I was thinking too--probably the easiest approach.

**Comment by ader1990** [comment]
Hello,

do you still have this requirement?

**Comment by embray** [comment]
I haven't needed to build an image in a while, so personally no.  But it still appears to be an issue.

**Comment by yasmindemiral** [comment]
I converted install.esd to install.wim otherwise it is not working.

**Comment by ader1990** [comment]
Closing issue, as there is not activity on it.
